# Generated by Django 4.0.3 on 2022-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pseudo', models.CharField(max_length=25)),
                ('nbre_access', models.IntegerField(default=0)),
            ],
        ),
    ]
