# Generated by Django 4.0.3 on 2022-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniURL', '0002_alter_miniurl_date_creation_alter_miniurl_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='long_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='nbre_access',
            field=models.IntegerField(default=0),
        ),
    ]
