# Generated by Django 4.0.3 on 2022-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniURL', '0003_alter_miniurl_date_creation_alter_miniurl_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='long_url',
            field=models.URLField(),
        ),
    ]
